### ISSUE TITLE
Camera calibration

### ISSUE THREAD

**Issue by yakir12** [FugroRoames/CoordinateTransformations.jl#48]
I got excited to see the new function `cameramap`, which brings us closer to being able to calibrate stationary cameras. I however am missing an example showing how we can use `cameramap` together with `PerspectiveMap` to convert 2D image coordinates to 3D real-world coordinates. 

While automating the whole process (by detecting a checkerboard) might be the ultimate step, I first must understand how it works manually... 

Thanks in advance!

**Comment by c42f** [comment]
A 2D image coordinate corresponds to a ray in 3D rather than a single point. So you can't really invert a `PerspectiveMap` without also supplying an assumed depth.

If you are looking to do camera calibration, you may want to do optimization by minimizing the distance in the 2D image plane between checkerboard intersections and some assumed model of the checkerboard. But I'm just guessing at a good approach; I suggest looking up some papers on how to do camera calibration effectively.

**Comment by yakir12** [comment]
OK, I read a tiny little bit and I definitely need to read a lot more...

I was under the wrong impression that most of the pieces were here and all that was missing is me understanding how to use them together to calibrate a camera. 

I guess that camera calibrations shouldn't reside in `CoordinateTransformations.jl`. So maybe once such a package forms we can decide on what goes where (e.g. `cameramap` might fit better in this future camera calibrations package). 

There also the matter of automatically detecting the checkerboards, I want to try [this](https://github.com/ftdlyc/libcbdetect). 

Feel free to close this since this is not about any issue with `CoordinateTransformations`, but it would be great to discuss these things...

**Comment by c42f** [comment]
Yes, I think camera calibration is out of scope for sure :-)

But this package could be used as one of the building blocks for it.
